org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.java.home=C:/Program Files/Java/jdk-21.0.11

# Minecraft / NeoForge
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.219
neo_version_range=[21.1.0,21.2)
loader_version_range=[4,)

# Parchment mappings
parchment_minecraft_version=1.21
parchment_mappings_version=2024.07.28

# Mod metadata
mod_id=tidesdelight
mod_name=TidesDelight
mod_license=GNU LGPL 3.0
mod_version=1.2.0-1.21.1
mod_group_id=net.felixlotionstein
mod_authors=Felix Lotionstein
mod_description=An expansion mod for Farmer's Delight focused on coastal and underwater ingredients, providing integration with the Tide mod.
