modLoader = "javafml"
loaderVersion = "[47,)" # Forge for Minecraft 1.20.1
license = "MIT"

[[mods]]
modId = "tidesdelight"
version = "1.1.0"
displayName = "Tide's Delight"
authors = "Felix Lotionstein"
description = '''An expansion mod for Farmer’s Delight focused on coastal and underwater ingredients, providing integration with the Tide mod. Brings new recipes, foods, and flavor rooted in the bounty of the sea.'''

[[dependencies."tidesdelight"]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies."tidesdelight"]]
modId = "farmersdelight"
mandatory = true
versionRange = "[1.2.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies."tidesdelight"]]
modId = "culturaldelights"
mandatory = true
versionRange = "[0.16.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies."tidesdelight"]]
modId = "tide"
mandatory = true
versionRange = "[2.0,)"
ordering = "NONE"
side = "BOTH"

